substitutions: # per device-specific substitutions (copy this only to the esphome web ui)
  name: "smart-plug-v2"
  friendly_name: "Smart Plug V2"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: ""
  device_description: "athom smart plug v2"
  project_name: "Athom Technology.Smart Plug V2"
  project_version: "2.0.1"
  relay_restore_mode: RESTORE_DEFAULT_OFF
  sensor_update_interval: 5s
  sensor_accuracy_decimals: "3"
  # Current Limit in Amps. AU Plug = 10. IL, BR, EU, UK, US Plug = 16.
  current_limit : "16"


packages:
  # device base packages
  device_base:
    url: https://github.com/Cahlil-Togonon/Smart-iLAB
    ref: main
    file: packages/device_base.yaml
    refresh: 5min


esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  area: "${room}"
  name_add_mac_suffix: true
  min_version: 2024.2.1
  project:
    name: "${project_name}"
    version: "${project_version}"


esp8266:
  board: esp8285
  restore_from_flash: true


preferences:
  flash_write_interval: 5min


logger:
  baud_rate: 0


uart:
  rx_pin: RX
  baud_rate: 4800
