packages:
  smart-plug-v2:
    url: https://github.com/Cahlil-Togonon/Smart-iLAB
    ref: main
    file: Athom/athom-smart-plug-v2.yaml
    refresh: 5min


globals:
  - id: "relay_state"
    type: std::string


mqtt:
  id: mqtt_sensor
  broker: !secret broker_ip
  port: !secret broker_port
  username: !secret broker_username
  password: !secret broker_password
  
  topic_prefix: null  # removes /state and /command topics
  reboot_timeout: 1min
  
  on_json_message: 
    topic: "athom_smart_plug_v2_${device_id}/relay"
    then: 
       - if: 
          condition: 
            lambda: !lambda |-
              if(x.containsKey("state")){
              if(x["state"] == "On"){
              id(relay_state) = "On";
              return true;
              }
              }
              id(relay_state) = "Off";
              return false;
          then:
            - switch.turn_on: relay
          else: 
            - switch.turn_off: relay


esphome:
  on_boot:
  - priority: -10
    then:
      - lambda: !lambda |-
          id(relay_state) = "Off";
  
      - switch.turn_off: relay


sensor:
  - platform: !extend cse7766
    current:
      id: current
    voltage:
      id: voltage
  - platform: !extend total_daily_energy
    id: total_daily_energy_sensor

script:
  - id: mqtt_publish_sensor_data
    then:
      - lambda: !lambda |-
          id(mqtt_sensor).publish_json("athom_smart_plug_v2_${device_id}/data", [=](JsonObject root){
          
          // timestamp
          root["timestamp"] = id(sntp_time).now().strftime("%Y-%m-%d %X");

          // sensor data
          root["current"] = id(current).state;
          root["energy"] = id(energy).state;
          root["power"] = id(power_sensor).state;
          root["total_daily_energy"] = id(total_daily_energy_sensor).state;
          root["total_energy"] = id(total_energy_sensor).state;
          root["voltage"] = id(voltage).state;

          // relay data
          root["state"] = id(relay_state);
          
          });


time:
  - platform: sntp
    on_time: 
      seconds: /10
      then: 
        - script.execute: mqtt_publish_sensor_data
