substitutions: # per device-specific substitutions (copy this only to the esphome web ui)
  static_ip:   AddIPAddressHere       # set to the target ip address of the device
  use_address: AddIPAddressHere       # set to the current ip address of the device for OTA flashing  
  api_key: "AddAPIKeyHere"

  ota_password: !secret ota_password
  log_level: DEBUG
  web_server_ota: "false"                # enable ota in the web server.
  esp_wifi_scan_internal: "true"         # set to false to show the full wifi scan results

  device_manufacturer: athom
  device_name: smart_plug_v2
  device_id: AddDeviceIDHere


packages:
  athom_smart_plug_v2:
    url: https://github.com/Julius-Ipac/Smart-iLAB
    ref: main
    file: Athom/athom-smart-plug-v2-super-minimal.yaml
    #file: Athom/athom-smart-plug-v2-minimal.yaml
    #file: Athom/athom-smart-plug-v2.yaml
    refresh: 5min
