substitutions: # per device-specific substitutions (copy this only to the esphome web ui)
  name: "smart-plug-v2"
  friendly_name: "Smart Plug V2"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: ""
  device_description: "athom smart plug v2"
  project_name: "Athom Technology.Smart Plug V2"
  project_version: "2.0.1"
  relay_restore_mode: RESTORE_DEFAULT_OFF
  sensor_update_interval: 5s
  sensor_accuracy_decimals: "3"
  # Current Limit in Amps. AU Plug = 10. IL, BR, EU, UK, US Plug = 16.
  current_limit : "16"
  
  wifi_ssid_1:          !secret wifi_ssid
  wifi_ssid_1_password: !secret wifi_password
  # wifi_bssid_1:         !secret wifi_bssid
  wifi_ssid_2:          !secret uly_wifi_ssid
  wifi_ssid_2_password: !secret uly_wifi_password
  gateway:              !secret gateway           # Set this to the IP address of the router. Often ends with .1
  subnet:               !secret subnet            # The subnet of the network

  dns_domain: ".local"                            # Define the domain for this device. example: .local (device will appear as xxx-xxxxx.local in DNS/DHCP logs)
  wifi_fast_connect: "false"                      # Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken
  ap_timeout: 1min
  power_save_mode: none
  reboot_timeout: 2min
  flash_write_interval: 10min

  timezone: ""                                    # Set timezone of the device. Can be entered in unix Country/Area format (i.e. "Australia/Sydney")


packages:
  wifi:
    url: https://github.com/Cahlil-Togonon/Smart-iLAB
    ref: main
    file: packages/base_packages/wifi.yaml
    refresh: 5min
  api:
    url: https://github.com/Cahlil-Togonon/Smart-iLAB
    ref: main
    file: packages/base_packages/api.yaml
    refresh: 5min
  ota:
    url: https://github.com/Cahlil-Togonon/Smart-iLAB
    ref: main
    file: packages/base_packages/ota.yaml
    refresh: 5min
  sensor:
    url: https://github.com/Cahlil-Togonon/Smart-iLAB
    ref: main
    file: packages/base_packages/sensor.yaml
    refresh: 5min
  button:
    url: https://github.com/Cahlil-Togonon/Smart-iLAB
    ref: main
    file: packages/base_packages/button.yaml
    refresh: 5min
  text_sensor:
    url: https://github.com/Cahlil-Togonon/Smart-iLAB
    ref: main
    file: packages/base_packages/text_sensor.yaml
    refresh: 5min
  time:
    url: https://github.com/Cahlil-Togonon/Smart-iLAB
    ref: main
    file: packages/base_packages/time.yaml
    refresh: 5min


esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  area: "${room}"
  name_add_mac_suffix: true
  min_version: 2024.2.1
  project:
    name: "${project_name}"
    version: "${project_version}"


esp8266:
  board: esp8285
  restore_from_flash: true


preferences:
  flash_write_interval: 5min


logger:
  baud_rate: 0


uart:
  rx_pin: RX
  baud_rate: 4800
