# AirGradient ONE - Board v9
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  name: "ag-one"
  friendly_name: "AG One"
  config_version: 2.0.1


packages:
  # device base packages
  device_base:
    url: https://github.com/Cahlil-Togonon/Smart-iLAB
    ref: main
    file: packages/device_base.yaml
    refresh: 5min

  # Air Gradient packages from MallocArray
  board: github://MallocArray/airgradient_esphome/packages/airgradient_esp32-c3_board.yaml
  pm_2.5: github://MallocArray/airgradient_esphome/packages/sensor_pms5003.yaml
  co2: github://MallocArray/airgradient_esphome/packages/sensor_s8.yaml
  temp_humidity: github://MallocArray/airgradient_esphome/packages/sensor_sht40.yaml
  tvoc: github://MallocArray/airgradient_esphome/packages/sensor_sgp41.yaml
  display: github://MallocArray/airgradient_esphome/packages/display_sh1106_multi_page.yaml
  led: github://MallocArray/airgradient_esphome/packages/led.yaml
  led_co2: github://MallocArray/airgradient_esphome/packages/led_co2.yaml
  airgradient_api: github://MallocArray/airgradient_esphome/packages/airgradient_api_esp32-c3.yaml
  hardware_watchdog: github://MallocArray/airgradient_esphome/packages/watchdog.yaml
  config_button: github://MallocArray/airgradient_esphome/packages/config_button.yaml
  wifi_sensor: github://MallocArray/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://MallocArray/airgradient_esphome/packages/sensor_uptime.yaml
  safe_mode: github://MallocArray/airgradient_esphome/packages/switch_safe_mode.yaml


globals:
  - id: actuator_state_changed
    restore_value: no
    type: 'bool'
    initial_value: 'false'
  - id: previous_light_state
    restore_value: no
    type: 'bool'
    initial_value: 'false'
  - id: previous_light_r
    restore_value: no
    type: 'float'
    initial_value: '0'
  - id: previous_light_g
    restore_value: no
    type: 'float'
    initial_value: '0'
  - id: previous_light_b
    restore_value: no
    type: 'float'
    initial_value: '0'
  - id: previous_light_brightness
    restore_value: no
    type: 'float'
    initial_value: '0'


mqtt:
  id: mqtt_sensor
  broker: !secret broker_ip
  port: !secret broker_port
  username: !secret broker_username
  password: !secret broker_password
  
  topic_prefix: null  # removes /state and /command subscriptions
  reboot_timeout: 1min
  
  on_json_message: 
    - topic: "airgradient_one_${device_id}/light"
      then: 
       - lambda: !lambda |-
            if(x["state"]=="On"){
            id(led_strip).current_values.set_state(static_cast<float>(1));
            } else {
            id(led_strip).current_values.set_state(static_cast<float>(0));
            }
            // values must be between 0 and 1
            id(led_strip).current_values.set_red(x["color"]["r"]);
            id(led_strip).current_values.set_green(x["color"]["g"]);
            id(led_strip).current_values.set_blue(x["color"]["b"]);
            id(led_strip).current_values.set_brightness(x["brightness"]);

  birth_message: 
    topic: "airgradient_one_${device_id}/data"
    payload: "airgradient_one_${device_id} online"
  
  will_message: 
    topic: "airgradient_one_${device_id}/data"
    payload: "airgradient_one_${device_id} offline"


esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${friendly_name}"
  name_add_mac_suffix: true             # recommended: use mac address as differentiator

  on_boot:
  - priority: -10
    then:
      - light.turn_off: led_strip


binary_sensor:
  - id: !extend config_button
    pin:
      ignore_strapping_warning: true  # Acknowledging that this is a strapping pin and should not have external pullup/down resistors  https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins


script:
  # publish sensor and actuator data 
  - id: mqtt_publish_sensor_data
    then:
      - lambda: |-
          id(mqtt_sensor).publish_json("airgradient_one_${device_id}/data", [=](JsonObject root){

          // date and time
          root["timestamp"] = id(sntp_time).now().strftime("%Y-%m-%d %X%z");

          // sensor data
          root["co2"]         = id(co2).state;
          root["temperature"] = id(temp).state;
          root["humidity"]    = id(humidity).state;
          root["nox"]         = id(nox).state;
          root["voc"]         = id(voc).state;
          root["pm_0_3"]      = id(pm_0_3um).state;
          root["pm_1_0"]      = id(pm_1_0).state;
          root["pm_2_5"]      = id(pm_2_5).state;
          root["pm_10_0"]     = id(pm_10_0).state;

          // led strip data
          root["state"] = id(led_strip_state);
          root["r"] = id(led_strip_values)["r"];
          root["g"] = id(led_strip_values)["g"];
          root["b"] = id(led_strip_values)["b"];
          root["brightness"] = id(led_strip_brightness);

          });
          
  # publish sensor and actuator data if an actuator's state changed
  - id: mqtt_publish_data_on_actuator_state_change
    then:
      - lambda: !lambda |-
          if(id(previous_light_state) != id(led_strip).current_values.is_on()){
            id(previous_light_state) = id(led_strip).current_values.is_on();
            id(actuator_state_changed) = true;
          }
          if(id(previous_light_r) != id(led_strip).current_values.get_red()){
            id(previous_light_r) = id(led_strip).current_values.get_red();
            id(actuator_state_changed) = true;
          }
          if(id(previous_light_g) != id(led_strip).current_values.get_green()){
            id(previous_light_g) = id(led_strip).current_values.get_green();
            id(actuator_state_changed) = true;
          }
          if(id(previous_light_b) != id(led_strip).current_values.get_blue()){
            id(previous_light_b) = id(led_strip).current_values.get_blue();
            id(actuator_state_changed) = true;
          }
          if(id(previous_light_brightness) != id(led_strip).current_values.get_brightness()){
            id(previous_light_brightness) = id(led_strip).current_values.get_brightness();
            id(actuator_state_changed) = true;
          }

          if(id(actuator_state_changed) == true){
            id(mqtt_publish_data).execute();
          }
          
          id(actuator_state_changed) = false;

time:
  # every 10 seconds, publish sensor and actuator data
  - platform: sntp
    on_time: 
      seconds: /10
      then: 
        - script.execute: mqtt_publish_data
  # every second, check if an actuator's state changed
  - platform: sntp
    on_time: 
      seconds: /1,/2,/3,/4,/5,/6,/7,/8,/9,/10
      then: 
        - script.execute: mqtt_publish_data_on_actuator_state_change
